[Draft] Updated Factory Boy Documentation
runtimerevolution/python-knowledge-base pull request #16
Opened 2022-11-22 09:39 UTC by pedro-inf-custodio

Added Maybe Method (Factory Boy) with example to the knowledge base .

2022-11-28 11:21 UTC, kenvontucky requested changes
lets move this file to the tests folder.

2022-11-28 11:21 UTC, kenvontucky commented on docs/factory_boy.md
> +class AuthorFactory(factory.django.DjangoModelFactory):
The example should follow the previous models, Music and so on.

2023-01-09 09:42 UTC, kenvontucky approved these changes

2023-01-19 11:00 UTC, JdFSilva approved these changes

2023-01-25 12:08 UTC, merged